---
platform: linux

inputs:
- name: code

run:
  path: sh
  args:
    - -exc
    - |
      cp code/. gopath/src/${MODULE}
      export GOPATH=$(pwd)/gopath:${GOPATH}
      cd gopath/src/${MODULE}
      go version; echo
      zb build

params:
  MODULE: "dummy"