---
platform: linux

inputs:
- name: code

run:
  path: sh
  args:
    - -exc
    - |
      git clone code gopath/src/${MODULE}
      export GOPATH=$(pwd)/gopath:${GOPATH}
      cd gopath/src/${MODULE}
      go version; echo
      zb lint -f --exclude=/usr/local/go

params:
  MODULE: "dummy"