---
platform: linux

inputs:
- name: git-id
  path: gopath/src/github.com/anothermemory/id

run:
  path: sh
  args:
    - -exc
    - |
      export GOPATH=$(pwd)/gopath:${GOPATH} && \
      cd gopath/src/github.com/anothermemory/id && \
      go version && \
      zb build && \
      zb lint -f --exclude=/usr/local/go && \
      go test -v ./...